import type { Field, FormSection } from "../crud-modal";

/* ============ USERS ============ */
export const userFields: Field[] = [
  { key: "name", label: "Full Name", type: "text", required: true, section: "Personal Information",
    description: "The user's complete legal name as it should appear on the platform.",
    placeholder: "e.g. Rajat Malhotra",
    tooltip: "This name will be displayed publicly on the user's profile and in all communications." },
  { key: "email", label: "Email Address", type: "email", required: true, section: "Personal Information",
    description: "Used for login, notifications, and account verification. Must be unique.",
    placeholder: "e.g. rajat@sportsphere.app",
    hint: "user@example.com" },
  { key: "password", label: "Password", type: "text", required: true, section: "Personal Information",
    description: "Minimum 8 characters. Will be encrypted before saving to database.",
    placeholder: "Enter a strong password",
    tooltip: "Use a mix of letters, numbers, and symbols for better security. Password is hashed using bcrypt." },
  { key: "phone", label: "Phone Number", type: "text", section: "Contact",
    description: "Optional. Used for SMS notifications and account recovery.",
    placeholder: "e.g. +91 98765 43210",
    hint: "+91 followed by 10 digits" },
  { key: "userType", label: "Account Type", type: "select", required: true, section: "Account",
    description: "Determines what features the user can access and which dashboard they see.",
    tooltip: "Admin = full access, Athlete/Team/Academy/Brand/Corporate = role-specific dashboards, Fan = view-only access.",
    options: [
      { value: "admin", label: "Admin — Full system access" },
      { value: "athlete", label: "Athlete — Player profile" },
      { value: "team", label: "Team / Club — Manage roster" },
      { value: "academy", label: "Academy — Training programs" },
      { value: "brand", label: "Brand — Sponsorships & campaigns" },
      { value: "corporate", label: "Corporate — Employee sports" },
      { value: "fan", label: "Fan — View & engage only" },
    ]},
  { key: "isActive", label: "Account Active", type: "toggle", section: "Account",
    description: "Inactive users cannot login but their data is preserved. Use this instead of deleting.",
    defaultValue: true },
  { key: "isVerified", label: "Email Verified", type: "toggle", section: "Account",
    description: "Mark as verified to skip the email confirmation process.",
    tooltip: "Manually verify trusted users (like partners or staff) who you've confirmed offline." },
];
export const userFormMeta: FormSection = {
  description: "Create a new user account. The user will be able to login with the email and password you set here.",
  tip: "Choose the Account Type carefully — it determines the entire dashboard experience for this user. You can change it later, but role-specific data (like athlete stats) may not transfer.",
};

/* ============ ATHLETES ============ */
export const athleteFields: Field[] = [
  { key: "name", label: "Full Name", type: "text", required: true, section: "Basic Information",
    description: "Athlete's full name as it should appear on their public profile.",
    placeholder: "e.g. Aarav Mehta" },
  { key: "sport", label: "Primary Sport", type: "select", required: true, section: "Basic Information",
    description: "The main sport this athlete plays. Used for filtering and matching with teams.",
    tooltip: "If the athlete plays multiple sports, pick the one they're most active in. You can add more sports later in their profile.",
    options: [
      { value: "Cricket", label: "Cricket" },
      { value: "Football", label: "Football (Soccer)" },
      { value: "Badminton", label: "Badminton" },
      { value: "Basketball", label: "Basketball" },
      { value: "Athletics", label: "Athletics (Track & Field)" },
      { value: "Tennis", label: "Tennis" },
      { value: "Hockey", label: "Hockey" },
      { value: "Volleyball", label: "Volleyball" },
    ]},
  { key: "level", label: "Current Level", type: "select", required: true, section: "Basic Information",
    description: "The athlete's competitive level. Helps teams find the right talent.",
    tooltip: "Amateur = plays for fun, College = university level, Semi-Pro = paid but not full-time, Professional = full-time paid athlete, National = represents country, U-23 State = under-23 state level.",
    options: [
      { value: "Amateur", label: "Amateur — Recreational player" },
      { value: "College", label: "College — University level" },
      { value: "Semi-Pro", label: "Semi-Pro — Paid, part-time" },
      { value: "Professional", label: "Professional — Full-time" },
      { value: "National", label: "National — Represents country" },
      { value: "U-23 State", label: "U-23 State — Under-23 state level" },
      { value: "ITF Circuit", label: "ITF Circuit — International tennis" },
    ]},
  { key: "city", label: "City / Location", type: "text", required: true, section: "Location",
    description: "Where the athlete is currently based. Helps with local opportunities.",
    placeholder: "e.g. Mumbai, IN",
    hint: "City, Country format" },
  { key: "age", label: "Age", type: "number", required: true, section: "Basic Information",
    description: "Current age in years. Must be between 5 and 80.",
    placeholder: "e.g. 21",
    tooltip: "Age is used for age-group eligibility in tournaments and scholarships." },
  { key: "initials", label: "Display Initials", type: "text", section: "Profile Display",
    description: "2-3 letter initials shown in avatar when no photo is uploaded.",
    placeholder: "e.g. AM",
    hint: "First letters of first and last name" },
  { key: "accentColor", label: "Accent Color (Gradient)", type: "text", section: "Profile Display",
    description: "Tailwind CSS gradient classes for the athlete's card/avatar background.",
    placeholder: "from-emerald-400 to-emerald-700",
    tooltip: "This is a Tailwind CSS gradient. Format: 'from-COLOR-400 to-COLOR-700'. Colors: emerald, amber, rose, sky, violet, teal, etc." },
  { key: "bio", label: "Bio / About", type: "textarea", section: "Profile Display",
    description: "Short biography shown on the athlete's profile page. Max 500 characters recommended.",
    placeholder: "e.g. 21-year-old footballer from Mumbai. Played for college team and now pursuing professional career..." },
  { key: "isVerified", label: "Verified Athlete", type: "toggle", section: "Status & Visibility",
    description: "Verified athletes get a blue checkmark and appear higher in search results.",
    tooltip: "Only mark as verified after confirming the athlete's identity and credentials (ID proof, past records, etc.)." },
  { key: "isFeatured", label: "Featured on Homepage", type: "toggle", section: "Status & Visibility",
    description: "Featured athletes appear on the homepage and get premium visibility.",
    tooltip: "Use sparingly — recommended 4-6 featured athletes at a time for best homepage layout." },
  { key: "isActive", label: "Profile Active", type: "toggle", section: "Status & Visibility",
    description: "Inactive profiles are hidden from public search but data is preserved.",
    defaultValue: true },
];
export const athleteFormMeta: FormSection = {
  description: "Add a new athlete to the platform. This profile will be visible to teams, brands, and academies looking for talent.",
  tip: "Fill in as much detail as possible — athletes with complete profiles get 3x more discovery from scouts and teams. The 'Level' field is especially important for matching with the right opportunities.",
};

/* ============ TEAMS ============ */
export const teamFields: Field[] = [
  { key: "name", label: "Team Name", type: "text", required: true, section: "Team Information",
    description: "Official name of the team, club, or franchise.",
    placeholder: "e.g. Bengal Tigers FC" },
  { key: "sport", label: "Sport", type: "select", required: true, section: "Team Information",
    description: "The sport this team competes in.",
    options: [
      { value: "Cricket", label: "Cricket" },
      { value: "Football", label: "Football (Soccer)" },
      { value: "Basketball", label: "Basketball" },
      { value: "Hockey", label: "Hockey" },
      { value: "Volleyball", label: "Volleyball" },
      { value: "Athletics", label: "Athletics" },
    ]},
  { key: "city", label: "Home City", type: "text", required: true, section: "Location",
    description: "Where the team is based. Used for regional tournaments.",
    placeholder: "e.g. Kolkata, IN" },
  { key: "level", label: "Competition Level", type: "select", required: true, section: "Team Information",
    description: "The highest level at which this team competes.",
    tooltip: "Grassroots = beginner/community, Club = local club, State = state-level competition, National = national league, Professional = paid professional league.",
    options: [
      { value: "Grassroots", label: "Grassroots — Community/beginner" },
      { value: "Club", label: "Club — Local competition" },
      { value: "State", label: "State — State-level" },
      { value: "National", label: "National — National league" },
      { value: "Professional", label: "Professional — Paid league" },
    ]},
  { key: "initials", label: "Team Initials", type: "text", section: "Branding",
    description: "Short abbreviation for the team logo/avatar.",
    placeholder: "e.g. BT",
    hint: "2-3 letters" },
  { key: "accentColor", label: "Brand Color (Gradient)", type: "text", section: "Branding",
    description: "Tailwind gradient for team cards and logo background.",
    placeholder: "from-emerald-400 to-emerald-700",
    tooltip: "Format: 'from-COLOR-400 to-COLOR-700'. Pick colors that match the team's brand identity." },
  { key: "description", label: "Team Description", type: "textarea", section: "About",
    description: "Brief history and description of the team. Shown on team profile page.",
    placeholder: "e.g. Founded in 2020, Bengal Tigers FC is a professional football club based in Kolkata..." },
  { key: "openTrials", label: "Open Trials Active", type: "toggle", section: "Recruitment",
    description: "Turn on if the team is currently recruiting players. Shows a 'Open Trials' badge.",
    tooltip: "When enabled, athletes can apply directly through the platform. Turn off once trials are complete." },
  { key: "isVerified", label: "Verified Team", type: "toggle", section: "Status",
    description: "Verified teams get a checkmark and appear in trusted listings." },
  { key: "isFeatured", label: "Featured Team", type: "toggle", section: "Status",
    description: "Featured teams appear prominently on the homepage." },
  { key: "isActive", label: "Profile Active", type: "toggle", section: "Status",
    description: "Inactive teams are hidden from public view.",
    defaultValue: true },
];
export const teamFormMeta: FormSection = {
  description: "Register a new team, club, or franchise. Teams can recruit players, manage their roster, and participate in events.",
  tip: "Enable 'Open Trials Active' if you're currently looking for players — this makes your team visible to athletes searching for opportunities. Remember to turn it off once recruitment is complete.",
};

/* ============ ACADEMIES ============ */
export const academyFields: Field[] = [
  { key: "name", label: "Academy Name", type: "text", required: true, section: "Academy Information",
    description: "Official name of the sports academy or training center.",
    placeholder: "e.g. Apex Cricket Academy" },
  { key: "sport", label: "Primary Sport", type: "select", required: true, section: "Academy Information",
    description: "The main sport the academy trains athletes in.",
    options: [
      { value: "Cricket", label: "Cricket" },
      { value: "Football", label: "Football" },
      { value: "Badminton", label: "Badminton" },
      { value: "Basketball", label: "Basketball" },
      { value: "Athletics", label: "Athletics" },
      { value: "Tennis", label: "Tennis" },
    ]},
  { key: "city", label: "City", type: "text", required: true, section: "Location",
    description: "Where the academy is located.",
    placeholder: "e.g. Mumbai, IN" },
  { key: "contactEmail", label: "Contact Email", type: "email", section: "Contact Information",
    description: "Public email for enquiries about academy programs.",
    placeholder: "e.g. info@apexcricket.in" },
  { key: "contactPhone", label: "Contact Phone", type: "text", section: "Contact Information",
    description: "Phone number for admissions and enquiries.",
    placeholder: "e.g. +91 98765 43210" },
  { key: "initials", label: "Academy Initials", type: "text", section: "Branding",
    description: "Short initials for the academy logo.",
    placeholder: "e.g. AC" },
  { key: "accentColor", label: "Brand Color (Gradient)", type: "text", section: "Branding",
    description: "Tailwind gradient for academy cards.",
    placeholder: "from-rose-400 to-rose-700" },
  { key: "isPartner", label: "Official Partner Academy", type: "toggle", section: "Partnership",
    description: "Partner academies get premium placement and can list programs on the platform.",
    tooltip: "Only enable for academies with a formal partnership agreement in place.",
    defaultValue: true },
  { key: "isFeatured", label: "Featured Academy", type: "toggle", section: "Status",
    description: "Featured academies appear on the homepage and academy hub." },
  { key: "isActive", label: "Profile Active", type: "toggle", section: "Status",
    description: "Inactive academies are hidden from public view.",
    defaultValue: true },
];
export const academyFormMeta: FormSection = {
  description: "Add a new sports academy. Academies can list training programs, attract talent, and partner with brands.",
  tip: "Make sure to fill in contact information — parents and athletes will use it to enquire about programs. Verified partner acadies get 5x more enquiries.",
};

/* ============ BRANDS ============ */
export const brandFields: Field[] = [
  { key: "name", label: "Brand Name", type: "text", required: true, section: "Brand Information",
    description: "Official company/brand name.",
    placeholder: "e.g. Velocity Sports" },
  { key: "industry", label: "Industry", type: "text", required: true, section: "Brand Information",
    description: "What industry does this brand belong to?",
    placeholder: "e.g. Apparel, Nutrition, Beverages, Media",
    hint: "Apparel, Nutrition, Footwear, Beverages, Media, etc." },
  { key: "partnershipType", label: "Partnership Type", type: "select", required: true, section: "Partnership Details",
    description: "The type of partnership this brand has with SportSphere.",
    tooltip: "Title Partner = top-tier naming rights, Endorsement = athlete endorsements, Team Sponsor = sponsors a team, Event Partner = sponsors events, Broadcast = media partner, Corporate = corporate wellness partner.",
    options: [
      { value: "Title Partner", label: "Title Partner — Naming rights" },
      { value: "Endorsement Partner", label: "Endorsement — Athlete endorsements" },
      { value: "Team Sponsor", label: "Team Sponsor — Sponsors a team" },
      { value: "Event Partner", label: "Event Partner — Sponsors events" },
      { value: "Broadcast Partner", label: "Broadcast — Media rights" },
      { value: "Corporate Partner", label: "Corporate — Employee wellness" },
    ]},
  { key: "initials", label: "Brand Initials", type: "text", section: "Branding",
    description: "Short initials for the brand logo.",
    placeholder: "e.g. VS" },
  { key: "accentColor", label: "Brand Color (Gradient)", type: "text", section: "Branding",
    description: "Tailwind gradient for brand cards.",
    placeholder: "from-emerald-400 to-emerald-700" },
  { key: "website", label: "Website URL", type: "text", section: "Contact",
    description: "Brand's official website. Shown on their profile.",
    placeholder: "https://velocitysports.in",
    hint: "Must include https://" },
  { key: "isActive", label: "Active Partner", type: "toggle", section: "Status",
    description: "Inactive brands are hidden from the partners showcase.",
    defaultValue: true },
];
export const brandFormMeta: FormSection = {
  description: "Add a new brand partner. Brands can sponsor athletes, teams, events, and run campaigns through the platform.",
  tip: "The partnership type determines how the brand appears across the platform. Choose 'Title Partner' for premium brands who want maximum visibility.",
};

/* ============ EVENTS ============ */
export const eventFields: Field[] = [
  { key: "title", label: "Event Title", type: "text", required: true, section: "Event Details",
    description: "Full name of the tournament, league, or competition.",
    placeholder: "e.g. Metro Premier Football Cup 2026" },
  { key: "sport", label: "Sport", type: "select", required: true, section: "Event Details",
    description: "Which sport is this event for?",
    options: [
      { value: "Cricket", label: "Cricket" },
      { value: "Football", label: "Football" },
      { value: "Badminton", label: "Badminton" },
      { value: "Basketball", label: "Basketball" },
      { value: "Volleyball", label: "Volleyball" },
      { value: "Golf", label: "Golf" },
      { value: "Athletics", label: "Athletics" },
      { value: "Hockey", label: "Hockey" },
    ]},
  { key: "eventType", label: "Event Type", type: "select", required: true, section: "Event Details",
    description: "The format of the competition.",
    tooltip: "Tournament = single/multi-day knockout, League = round-robin + playoffs, Pro-Am = professional + amateur pairs, Corporate = inter-company, Community = open community event.",
    options: [
      { value: "tournament", label: "Tournament — Knockout format" },
      { value: "league", label: "League — Round-robin + playoffs" },
      { value: "pro-am", label: "Pro-Am — Pro + amateur pairs" },
      { value: "corporate", label: "Corporate — Inter-company" },
      { value: "community", label: "Community — Open event" },
    ]},
  { key: "city", label: "Host City", type: "text", required: true, section: "Location & Venue",
    description: "Where the event will be held.",
    placeholder: "e.g. Mumbai, IN" },
  { key: "venue", label: "Venue / Stadium", type: "text", section: "Location & Venue",
    description: "Specific venue name where matches will be played.",
    placeholder: "e.g. Cooperage Stadium" },
  { key: "startDate", label: "Start Date", type: "date", required: true, section: "Schedule",
    description: "First day of the event. Format: YYYY-MM-DD.",
    placeholder: "2026-08-14" },
  { key: "endDate", label: "End Date", type: "date", required: true, section: "Schedule",
    description: "Last day of the event. Must be same as or after start date.",
    placeholder: "2026-08-28" },
  { key: "status", label: "Event Status", type: "select", section: "Status",
    description: "Current status of the event.",
    options: [
      { value: "upcoming", label: "Upcoming — Not started yet" },
      { value: "live", label: "Live — Currently happening" },
      { value: "completed", label: "Completed — Finished" },
      { value: "cancelled", label: "Cancelled — Called off" },
    ]},
  { key: "registrationOpen", label: "Registration Open", type: "toggle", section: "Registration",
    description: "Allow athletes/teams to register for this event.",
    tooltip: "Turn this on when registrations open, and turn off when the deadline passes or capacity is reached.",
    defaultValue: true },
  { key: "maxParticipants", label: "Max Participants", type: "number", section: "Registration",
    description: "Maximum number of participants/teams allowed.",
    placeholder: "e.g. 32" },
  { key: "isFeatured", label: "Featured Event", type: "toggle", section: "Status",
    description: "Featured events appear on the homepage carousel." },
];
export const eventFormMeta: FormSection = {
  description: "Create a new tournament, league, or competition. Events can accept registrations and showcase results.",
  tip: "Set the status to 'Upcoming' and keep registration open until the deadline. Once the event starts, change status to 'Live', and to 'Completed' when finished. This keeps the platform accurate for users.",
};

/* ============ BLOG ============ */
export const blogFields: Field[] = [
  { key: "title", label: "Post Title", type: "text", required: true, section: "Content",
    description: "The headline of the blog post. Should be catchy and descriptive.",
    placeholder: "e.g. How AI Matching Is Quietly Reshaping Sports Recruitment" },
  { key: "category", label: "Category", type: "select", required: true, section: "Content",
    description: "Helps users find related articles.",
    options: [
      { value: "Platform Updates", label: "Platform Updates — News about SportSphere" },
      { value: "Sports News", label: "Sports News — General sports updates" },
      { value: "Press Releases", label: "Press Releases — Official announcements" },
      { value: "Insights", label: "Insights — Analysis & opinion" },
      { value: "CSR", label: "CSR — Community/social initiatives" },
    ]},
  { key: "excerpt", label: "Excerpt / Summary", type: "textarea", required: true, section: "Content",
    description: "Short summary shown in the blog listing. 1-2 sentences that hook the reader.",
    placeholder: "e.g. We dive into the recommendation layer behind SportSphere and how it ranks athletes against team needs.",
    tooltip: "This appears on the blog listing page. Make it compelling — it determines if people click through to read the full article." },
  { key: "content", label: "Full Content (HTML)", type: "textarea", required: true, section: "Content",
    description: "The complete article body. Supports HTML tags like <p>, <h2>, <strong>, <a>.",
    placeholder: "<p>Your article content here...</p>",
    tooltip: "Use HTML for formatting: <p> for paragraphs, <h2> for subheadings, <strong> for bold, <a href='...'> for links. Keep paragraphs short for readability." },
  { key: "author", label: "Author Name", type: "text", required: true, section: "Author & Publishing",
    description: "Name of the person who wrote this article.",
    placeholder: "e.g. Rajat Malhotra" },
  { key: "status", label: "Publishing Status", type: "select", section: "Author & Publishing",
    description: "Draft = not visible, Published = live on site, Archived = hidden from listing.",
    defaultValue: "draft",
    options: [
      { value: "draft", label: "Draft — Not published yet" },
      { value: "published", label: "Published — Live on website" },
      { value: "archived", label: "Archived — Hidden from listing" },
    ]},
  { key: "isFeatured", label: "Featured Post", type: "toggle", section: "Author & Publishing",
    description: "Featured posts appear at the top of the blog page.",
    tooltip: "Only mark 1-2 posts as featured at a time for best layout." },
];
export const blogFormMeta: FormSection = {
  description: "Write a new blog post or news article. Posts can be saved as drafts and published when ready.",
  tip: "Write your excerpt first — it's the most important field for getting readers to click. A good excerpt increases readership by 2x. Save as draft while writing, then publish when ready.",
};

/* ============ SERVICES ============ */
export const serviceFields: Field[] = [
  { key: "title", label: "Service Title", type: "text", required: true, section: "Basic Information",
    description: "Name of the service pillar (e.g. 'Connects Athletes').",
    placeholder: "e.g. Connects Athletes" },
  { key: "tagline", label: "Tagline", type: "text", required: true, section: "Basic Information",
    description: "A short catchy phrase shown under the title.",
    placeholder: "e.g. Discover opportunities. Build a career." },
  { key: "icon", label: "Icon Name (Lucide)", type: "text", section: "Basic Information",
    description: "Lucide icon name. Used for the service card icon.",
    placeholder: "e.g. dumbbell",
    hint: "lowercase, hyphenated (dumbbell, user-group, trophy)",
    tooltip: "Browse icons at lucide.dev. Use lowercase names with hyphens, e.g. 'dumbbell', 'users', 'graduation-cap', 'handshake', 'building-2', 'trophy', 'heart', 'sparkles'." },
  { key: "sortOrder", label: "Display Order", type: "number", section: "Basic Information",
    description: "Lower numbers appear first. 1 = first, 8 = last.",
    placeholder: "e.g. 1",
    defaultValue: 1 },
  { key: "shortDescription", label: "Short Description", type: "textarea", required: true, section: "Content",
    description: "One-line summary shown on service cards.",
    placeholder: "e.g. We help athletes discover opportunities with teams, brands, and academies." },
  { key: "overview", label: "Full Overview", type: "textarea", required: true, section: "Content",
    description: "Detailed paragraph explaining the service. Shown on the service detail page.",
    placeholder: "Write 2-3 sentences explaining what this service does and who it's for..." },
  { key: "forWhomTitle", label: "For Whom — Title", type: "text", required: true, section: "Target Audience",
    description: "Heading for the 'For Whom' section (e.g. 'For Athletes').",
    placeholder: "e.g. For Athletes" },
  { key: "forWhomBody", label: "For Whom — Description", type: "textarea", required: true, section: "Target Audience",
    description: "Who is this service for and what they get.",
    placeholder: "e.g. Create a verified profile, showcase stats, and get discovered by scouts..." },
  { key: "ctaLabel", label: "Call-to-Action Button Text", type: "text", required: true, section: "Call to Action",
    description: "Text on the action button (e.g. 'Create Your Profile').",
    placeholder: "e.g. Create Your Athlete Profile" },
  { key: "hubSlug", label: "Hub Page Slug", type: "text", section: "Navigation",
    description: "Which hub page this service links to.",
    placeholder: "e.g. athletes-hub",
    hint: "athletes-hub, teams-hub, academies-hub, etc." },
  { key: "isActive", label: "Service Active", type: "toggle", section: "Status",
    description: "Inactive services are hidden from the website.",
    defaultValue: true },
];
export const serviceFormMeta: FormSection = {
  description: "Edit one of the 8 service pillars shown on the homepage and services page.",
  tip: "The tagline and short description are what users see first on the homepage. Make them count — clear, benefit-focused copy performs 40% better.",
};

/* ============ SUCCESS STORIES ============ */
export const storyFields: Field[] = [
  { key: "title", label: "Story Title", type: "text", required: true, section: "Story Information",
    description: "Headline that captures the outcome.",
    placeholder: "e.g. From College League to Pro Contract in One Window" },
  { key: "subject", label: "Subject (Who/What)", type: "text", required: true, section: "Story Information",
    description: "The athlete, team, academy, or brand this story is about.",
    placeholder: "e.g. Aarav Mehta" },
  { key: "sport", label: "Sport", type: "text", required: true, section: "Story Information",
    description: "Which sport is this story related to?",
    placeholder: "e.g. Football",
    hint: "or 'Multi-sport' for cross-sport stories" },
  { key: "outcome", label: "Outcome / Result", type: "text", required: true, section: "Story Information",
    description: "The key achievement in a few words.",
    placeholder: "e.g. Pro Contract with Bengal Tigers FC",
    hint: "Short, impactful result" },
  { key: "excerpt", label: "Excerpt", type: "textarea", required: true, section: "Content",
    description: "1-2 sentence summary shown in the listing.",
    placeholder: "e.g. Aarav uploaded 3 match clips and updated his stats. Within 6 weeks, he signed his first pro deal." },
  { key: "content", label: "Full Story", type: "textarea", required: true, section: "Content",
    description: "Complete case study with details, quotes, and results.",
    placeholder: "Write the full story here..." },
  { key: "isFeatured", label: "Featured Story", type: "toggle", section: "Status",
    description: "Featured stories appear on the homepage." },
  { key: "isActive", label: "Story Active", type: "toggle", section: "Status",
    description: "Inactive stories are hidden.",
    defaultValue: true },
];
export const storyFormMeta: FormSection = {
  description: "Create a success story or case study showcasing real outcomes from the platform.",
  tip: "Use real names and real numbers (e.g. '+104% Enrolment') — specific outcomes build more trust than vague claims. Get permission before using client names.",
};

/* ============ TESTIMONIALS ============ */
export const testimonialFields: Field[] = [
  { key: "quote", label: "Testimonial Quote", type: "textarea", required: true, section: "Quote",
    description: "The exact words from the person. Keep it authentic — edit minimally.",
    placeholder: "e.g. I went from playing college football to a pro trial in 6 weeks. The platform changed my career.",
    tooltip: "Best testimonials are 1-3 sentences, specific, and mention a real outcome. Avoid generic praise like 'great service'." },
  { key: "name", label: "Person's Name", type: "text", required: true, section: "Person",
    description: "Full name of the person giving the testimonial.",
    placeholder: "e.g. Aarav Mehta" },
  { key: "role", label: "Role / Title", type: "text", required: true, section: "Person",
    description: "Their role and affiliation.",
    placeholder: "e.g. Athlete, Football",
    hint: "Role, Sport/Company" },
  { key: "initials", label: "Initials", type: "text", section: "Person",
    description: "For avatar display.",
    placeholder: "e.g. AM" },
  { key: "accentColor", label: "Accent Color (Gradient)", type: "text", section: "Display",
    description: "Tailwind gradient for the testimonial card.",
    placeholder: "from-emerald-400 to-emerald-700" },
  { key: "sortOrder", label: "Display Order", type: "number", section: "Display",
    description: "Lower numbers appear first.",
    placeholder: "e.g. 1" },
  { key: "isActive", label: "Active", type: "toggle", section: "Status",
    description: "Show this testimonial on the website.",
    defaultValue: true },
];
export const testimonialFormMeta: FormSection = {
  description: "Add a testimonial from a user, partner, or client. Testimonials appear on the homepage.",
  tip: "Get written permission before publishing someone's quote. Specific testimonials (with real results) convert 3x better than generic ones.",
};

/* ============ PARTNERS ============ */
export const partnerFields: Field[] = [
  { key: "name", label: "Partner Name", type: "text", required: true, section: "Partner Information",
    description: "Name of the team, academy, brand, or organization.",
    placeholder: "e.g. Bengal Tigers FC" },
  { key: "tag", label: "Category Tag", type: "text", required: true, section: "Partner Information",
    description: "Type of partner (shown as a label).",
    placeholder: "e.g. Football, Cricket, Brand, League",
    hint: "Sport name or 'Brand'/'League'/'Corporate'" },
  { key: "sortOrder", label: "Display Order", type: "number", section: "Display",
    description: "Order in the scrolling trust bar. Lower = first.",
    placeholder: "e.g. 1" },
  { key: "isActive", label: "Active", type: "toggle", section: "Status",
    description: "Show this partner in the trust bar.",
    defaultValue: true },
];
export const partnerFormMeta: FormSection = {
  description: "Add a partner to the scrolling trust bar on the homepage.",
  tip: "Partners in the trust bar build credibility. Add 8-12 partners for the best visual effect in the scrolling strip.",
};

/* ============ COMMUNITY ============ */
export const communityFields: Field[] = [
  { key: "authorName", label: "Author Name", type: "text", required: true, section: "Author",
    description: "Name of the person posting.",
    placeholder: "e.g. Aarav Mehta" },
  { key: "authorHandle", label: "Author Handle", type: "text", required: true, section: "Author",
    description: "Username with @ symbol.",
    placeholder: "e.g. @aaravm",
    hint: "starts with @" },
  { key: "authorRole", label: "Author Role", type: "select", required: true, section: "Author",
    description: "What type of user is posting?",
    options: [
      { value: "Athlete", label: "Athlete" },
      { value: "Academy", label: "Academy" },
      { value: "Brand", label: "Brand" },
      { value: "Coach", label: "Coach" },
      { value: "Fan", label: "Fan" },
      { value: "Team", label: "Team" },
    ]},
  { key: "content", label: "Post Content", type: "textarea", required: true, section: "Post",
    description: "The text of the post. Max 2000 characters.",
    placeholder: "e.g. Signed my first pro contract today! Grateful to everyone on this platform. ⚽" },
  { key: "tag", label: "Tag / Category", type: "text", section: "Post",
    description: "Optional label for the post.",
    placeholder: "e.g. Athlete Spotlight, Academy News, Opportunity",
    hint: "Athlete Spotlight, Academy News, Opportunity, etc." },
  { key: "isPinned", label: "Pinned Post", type: "toggle", section: "Status",
    description: "Pinned posts appear at the top of the feed.",
    tooltip: "Use sparingly — only pin important announcements or opportunities. 1-2 pinned posts max." },
  { key: "isActive", label: "Post Active", type: "toggle", section: "Status",
    description: "Inactive posts are hidden from the feed.",
    defaultValue: true },
];
export const communityFormMeta: FormSection = {
  description: "Create a community post. Posts appear in the social feed visible to all users.",
  tip: "Posts with emojis and real updates (like signing a contract or winning a match) get 5x more engagement. Use the tag field to help users filter content.",
};

/* ============ ENQUIRIES (status update only) ============ */
export const enquiryFields: Field[] = [
  { key: "status", label: "Enquiry Status", type: "select", required: true, section: "Update Status",
    description: "Change the status to track progress.",
    options: [
      { value: "new", label: "New — Just received, not yet reviewed" },
      { value: "in_progress", label: "In Progress — Being handled" },
      { value: "resolved", label: "Resolved — Completed successfully" },
      { value: "rejected", label: "Rejected — Declined or invalid" },
    ]},
  { key: "adminNotes", label: "Admin Notes (Internal)", type: "textarea", section: "Update Status",
    description: "Private notes for your team. Not visible to the enquirer.",
    placeholder: "e.g. Called customer, they want a corporate cricket league for 200 employees. Sent proposal on 15th." },
];
export const enquiryFormMeta: FormSection = {
  description: "Update the status and add internal notes for this enquiry.",
  tip: "Add detailed admin notes so your team knows what's been done. Setting status to 'Resolved' automatically records the resolution timestamp.",
};

/* ============ ROLES ============ */
export const roleFields: Field[] = [
  { key: "name", label: "Role Name (System)", type: "text", required: true, section: "Role Information",
    description: "Internal system name. Use lowercase with hyphens.",
    placeholder: "e.g. moderator",
    hint: "lowercase, no spaces",
    tooltip: "This is the internal identifier used in code. Once created, it's hard to change. Use simple lowercase names like 'admin', 'editor', 'moderator'." },
  { key: "displayName", label: "Display Name", type: "text", required: true, section: "Role Information",
    description: "Human-friendly name shown in the admin panel.",
    placeholder: "e.g. Moderator" },
  { key: "description", label: "Description", type: "textarea", section: "Role Information",
    description: "What can users with this role do?",
    placeholder: "e.g. Can moderate community posts and approve/reject content." },
];
export const roleFormMeta: FormSection = {
  description: "Create a new user role. Roles determine what users can access and do on the platform.",
  tip: "Plan role permissions carefully. The 'admin' role has full access — only assign to trusted staff. Create custom roles like 'moderator' for limited access.",
};
